---
- hosts: ucp-secondary
  remote_user: root
  tasks:
  - include: docker-engine.yaml

  - name: Copy configuration file
    copy: src=/tmp/backup.tar dest=/root/backup.tar

  - name: Copy fingerprint
    copy: src=/tmp/fingerprint dest=/root/fingerprint


  - name: Install Docker UCP. It will take a few minutes...
    shell: 'docker run --rm -it --name ucp -v /var/run/docker.sock:/var/run/docker.sock -v /root/backup.tar:/backup.tar docker/ucp join --replica --passphrase "dockerSecret2016" --url {{ url }} --fingerprint `cat /root/fingerprint` --admin-username admin --admin-password orca'
