---
- hosts: ucp-primary
  remote_user: root
  tasks:
  - include: docker-engine.yaml

  - name: Obtain IP address
    shell: grep {{ ansible_fqdn }} /etc/hosts | awk '{print $1}'
    register: host_ip

  - debug: msg="the IP address is {{ host_ip.stdout }}"

  - debug: msg="The License file is {{ ucp_license_file }}"

  - name: Install Docker UCP. It will take a few minutes...
    shell: 'docker run --rm -it --name ucp -v /var/run/docker.sock:/var/run/docker.sock -v {{ ucp_license_file }}:/docker_subscription.lic docker/ucp install --host-address {{ host_ip.stdout }}'
    ignore_errors: yes

  - name: Retrieve UCP Instance ID
    shell: docker run --rm -it --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp  id | grep -v INFO
    register: ucp_instance_id

  - debug: msg="the UCP instance ID is {{ ucp_instance_id }}"
  - name: Obtain fingerprint
    shell: docker run --rm -i --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp  fingerprint 2>/dev/null | awk '{print $2}' | cut -f2 -d= > /tmp/fingerprint

  - name: Copy fingerprint to desktop
    fetch: src=/tmp/fingerprint dest=/tmp/ flat=yes

  - name: Back up configuration
    shell: docker run --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp backup --root-ca-only --passphrase "dockerSecret2016" --id {{ ucp_instance_id.stdout }} > /tmp/backup.tar

  - name: Copy configuration to desktop
    fetch: src=/tmp/backup.tar dest=/tmp/ flat=yes
