---
- hosts: ucp-secondary
  remote_user: root
  tasks:
  - include: docker-engine.yaml

  - name: Copy configuration file
    copy: src=/tmp/backup.tar dest=/root/backup.tar

  - name: Copy token
    copy: src=/tmp/manager-token dest=/root/manager-token


  - name: Install Docker UCP. It will take a few minutes...
    shell: 'docker swarm join --token `cat /root/manager-token` {{ ucp1 }}:2377'
